config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :publications
  resources :people
  resources :faculties
  resources :welcome
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  validates :name, presence: true
  validates :code, presence: true
  has_many :people
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :faculty
  has_many :publications

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :code, :note)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:fullname, :email, :username, :faculty_id)
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:title, :release_date, :abstract, :person_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/faculties/_form.html.erb
<%= form_with(model: faculty, local: true) do |form| %>
  <% if faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>
      <ul>
        <% faculty.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :code %>
    <%= form.text_field :code, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', :class => 'btn btn-primary faculty-brn'%>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h2 class="testujeme">Editing Faculty</h2>

<%= render 'form', faculty: @faculty %>

<div class="btn-group faculty-brn" role="group" aria-label="Basic example">
  <%= link_to 'Show', @faculty, class: "btn btn-primary" %> |
  <%= link_to 'Back', faculties_path, class: "btn btn-primary" %>
</div>

app/views/faculties/index.html.erb
<h1 class="testujeme">Faculties</h1>

<table class="table table-hover tbl">
  <thead>
  <tr>
    <th scope="col">Name</th>
    <th scope="col">Code</th>
    <th scope="col">Note</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @faculties.each do |faculty| %>
    <tr>
      <td><%= faculty.name %></td>
      <td><%= faculty.code %></td>
      <td><%= faculty.note %></td>
      <td>
        <div class="btn-group float-right" role="group" aria-label="Basic example">
          <%= link_to 'Show', faculty, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_faculty_path(faculty), class: "btn btn-primary" %>
          <%= link_to 'Destroy', faculty, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path, class: "btn btn-primary" %>

app/views/faculties/new.html.erb
<h2 class="testujeme">New Faculty</h2>

<%= render 'form', faculty: @faculty %>

<%= link_to 'Back', faculties_path, class: "btn btn-primary faculty-brn" %>

app/views/faculties/show.html.erb
<h2 class="testujeme">Faculty detail</h2>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @faculty.code %>
</p>

<p>
  <strong>Note:</strong>
  <%= @faculty.note %>
</p>

<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Edit', edit_faculty_path(@faculty), class: "btn btn-primary" %> |
  <%= link_to 'Back', faculties_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Publisher</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/faculties">Faculties</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/people">People</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/publications">Publications</a>
      </li>
    </ul>
  </div>
</nav>

<div class="nevim">
  <%= yield %>
</div>
</body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>
      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :faculty_id %>
    <%= form.select :faculty_id, options_for_select(Faculty.all.map { |f| [f.name, f.id] }), {}, {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary faculty-brn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h2 class="testujeme">Editing Person</h2>

<%= render 'form', person: @person %>

<div class="btn-group faculty-brn" role="group" aria-label="Basic example">
  <%= link_to 'Show', @person, class: "btn btn-primary" %> |
  <%= link_to 'Back', people_path, class: "btn btn-primary" %>
</div>

app/views/people/index.html.erb
<h1 class="testujeme">People</h1>


<table class="table table-hover tbl">
  <thead>
  <tr>
    <th scope="col">Fullname</th>
    <th scope="col">Email</th>
    <th scope="col">Username</th>
    <th scope="col">Faculty</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td><%= person.fullname %></td>
      <td><%= person.email %></td>
      <td><%= person.username %></td>
      <td><%= person.faculty_id %></td>
      <td>
        <div class="btn-group float-right" role="group" aria-label="Basic example">
          <%= link_to 'Show', person, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_person_path(person), class: "btn btn-primary" %>
          <%= link_to 'Destroy', person, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Person', new_person_path, class: "btn btn-primary" %>

app/views/people/new.html.erb
<h1 class="testujeme">New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path, class: "btn btn-primary faculty-brn" %>

app/views/people/show.html.erb
<h2 class="testujeme">Person detail</h2>

<p>
  <strong>Fullname:</strong>
  <%= @person.fullname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @person.username %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @person.faculty_id %>
</p>
<table class="table table-hover tbl">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Release date</th>
    <th scope="col">Abstract</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @person.publications.each do |publication| %>
    <tr>
      <td><%= publication.title %></td>
      <td><%= publication.release_date %></td>
      <td><%= publication.abstract %></td>
      <td>
        <div class="btn-group float-right" role="group" aria-label="Basic example">
          <%= link_to 'Show', publication, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_publication_path(publication), class: "btn btn-primary" %>
          <%= link_to 'Destroy', publication, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br/>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Edit', edit_person_path(@person), class: "btn btn-primary" %> |
  <%= link_to 'Back', people_path, class: "btn btn-primary" %>
</div>

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, required: true, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :release_date %>
    <%= form.date_select :release_date, {}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :abstract %>
    <%= form.text_area :abstract,class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :person_id %>
    <%= form.select :person_id, options_for_select(Person.all.map { |f| [f.fullname, f.id] }), {}, {class: "form-control"} %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary faculty-brn' %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h2 class="testujeme">Editing Publication</h2>

<%= render 'form', publication: @publication %>


<div class="btn-group faculty-brn" role="group" aria-label="Basic example">
  <%= link_to 'Show', @publication, class: "btn btn-primary" %> |
  <%= link_to 'Back', publications_path, class: "btn btn-primary" %>
</div>

app/views/publications/index.html.erb
<h1 class="testujeme">Publications</h1>

<table class="table table-hover tbl">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Release date</th>
    <th scope="col">Abstract</th>
    <th scope="col">Person</th>
    <th scope="col">Published</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @publications.each do |publication| %>
    <tr>
      <td><%= publication.title %></td>
      <td><%= publication.release_date %></td>
      <td><%= publication.abstract %></td>
      <td><%= publication.person_id %></td>
      <td><%= publication.release_date < DateTime.now %></td>

      <td>
        <div class="btn-group float-right" role="group" aria-label="Basic example">
          <%= link_to 'Show', publication, class: "btn btn-primary" %>
          <%= link_to 'Edit', edit_publication_path(publication), class: "btn btn-primary" %>
          <%= link_to 'Destroy', publication, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-primary" %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publication', new_publication_path, class: "btn btn-primary" %>

app/views/publications/new.html.erb
<h1 class="testujeme">New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path, class: "btn btn-primary faculty-brn" %>

app/views/publications/show.html.erb
<h2 class="testujeme">Publication detail</h2>
<p>
  <strong>Title:</strong>
  <%= @publication.title %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @publication.release_date %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @publication.abstract %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= Person.find(@publication.person_id).fullname %>
</p>

<p>
  <strong>Publisher's faculty:</strong>
  <%= Faculty.find(Person.find(@publication.person_id).faculty_id).name %>
</p>

<br/>
<div class="btn-group" role="group" aria-label="Basic example">
  <%= link_to 'Edit', edit_publication_path(@publication), class: "btn btn-primary" %> |
  <%= link_to 'Back', publications_path, class: "btn btn-primary" %>
</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>